export const CHANGE_REGISTER_DIALOG_VISABLE = 'user/CHANGE_REGISTER_DIALOG_VISABLE'
export const OPEN_REGISTER_DIALOG = 'user/OPEN_REGISTER_DIALOG'
export const CLOSE_REGISTER_DIALOG = 'user/CLOSE_REGISTER_DIALOG'
